---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    pkg: 
      - npm
      - build-essential

- name: "Install PM2"
  shell: npm install pm2 -g

- name: "Create Web Directory"
  become: yes
  shell: mkdir ~/web

- name: "Copy Web Server"
  become: yes
  copy:
    src: /home/ec2-user/ex2/roles/setup/files/index.js 
    dest: /web/

- name: "Start Web Server"
  become: yes
  shell: pm2 start /web/index.js -f
